### ISSUE TITLE
The tests check Float80 on platforms like AArch64 where it is unavailable

### ISSUE THREAD

**Issue by buttaface** [apple/swift-numerics#131]
I periodically check this package on Android AArch64 by building it and running its tests, and compiling the tests broke after #123 was merged this week. Also, unrelated but the main branch doesn't build with Swift 5.2 since #111, so I revert that locally.

**Comment by stephentyrone** [comment]
The issue with #111 was fixed a long time ago, IIRC; are you still having trouble with it?

**Comment by buttaface** [comment]
>The issue with #111 and 5.2 was fixed a long time ago, IIRC.

Nope, still there with the official Swift 5.2.4 release for Ubuntu 20.04 x86_64 building your latest commit 189f072 from the main branch (reproducible on Android too):

```
> swift build -j 2
[13/13] Compiling ComplexModule Differentiable.swift
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:28:3: error: unknown attribute 'derivative'
  @derivative(of: real)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:36:3: error: unknown attribute 'derivative'
  @derivative(of: imaginary)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:47:3: error: unknown attribute 'derivative'
  @derivative(of: +)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:55:3: error: unknown attribute 'derivative'
  @derivative(of: -)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:63:3: error: unknown attribute 'derivative'
  @derivative(of: *)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:71:3: error: unknown attribute 'derivative'
  @derivative(of: /)
  ^
/home/butta/swift-numerics/Sources/ComplexModule/Differentiable.swift:79:3: error: unknown attribute 'derivative'
  @derivative(of: conjugate)
  ^
```
As for this issue, you missed one:
```
> swift test -j 9 --enable-test-discovery
[6/13] Compiling ComplexTests ApproximateEqualityTests.swift
/data/data/com.termux/files/home/src/swift-numerics/Tests/ComplexTests/ApproximateEqualityTests.swift:52:18: error: 'Float80' is unavailable: Float80 is not available on target platform.
    testSpecials(Float80.self)
                 ^~~~~~~
Swift.Float80:2:23: note: 'Float80' has been explicitly marked unavailable here
@frozen public struct Float80 {
                      ^
```

**Comment by stephentyrone** [comment]
Interesting. @rxwei, it looks like the Swift 5.2.4 Ubuntu toolchain has the _Differentiation module, but doesn't provide the `@derivative` attribute; is that expected, or is the toolchain broken somehow?

**Comment by stephentyrone** [comment]
#133 resolves the remaining Float80 issue.

**Comment by buttaface** [comment]
Yep, all tests pass again on Android AArch64 with #111 reverted.

**Comment by stephentyrone** [comment]
Thanks for confirming. I'll follow-up with the differentiable folks and figure out what we should do about that issue.

**Comment by rxwei** [comment]
Most of differentiation was unavailable until 5.3 even though the `_Differentiation` module existed. Perhaps we can add a Swift version check in addition to `canImport`.

**Comment by stephentyrone** [comment]
I'm confused; this was certainly working on macOS/5.2.x. Either way, is the right fix here to simply remove it on master and leave it on the swift-5.3 branch?

**Comment by rxwei** [comment]
Had a discussion with Steve offline.  AutoDiff was not fully upstreamed and not considered fully functional until 5.3, so it may be better to remove derivatives from master for now, until there's a branch like master-next for adopting the latest compiler features.

**Comment by stephentyrone** [comment]
https://github.com/apple/swift-numerics/pull/134

**Comment by stephentyrone** [comment]
This should be resolved now that #136 is merged to master, but I'm leaving it open for @buttaface to confirm.

**Comment by buttaface** [comment]
Yep, all fixed now, thanks.
